const ascendancies = [
  { class: "Warrior",    name: "Titan" },
  { class: "Warrior",    name: "Warbringer" },
  { class: "Ranger",     name: "Deadeye" },
  { class: "Ranger",     name: "Pathfinder" },
  { class: "Witch",      name: "Infernalist" },
  { class: "Witch",      name: "Blood Mage" },
  { class: "Sorceress",  name: "Stormweaver" },
  { class: "Sorceress",  name: "Chronomancer" },
  { class: "Mercenary",  name: "Witchhunter" },
  { class: "Mercenary",  name: "Gemling Legionnaire" },
  { class: "Monk",       name: "Invoker" },
  { class: "Monk",       name: "Acolyte of Chayula" },
];

const skillGems = [
  // Warrior
  "Boneshatter",
  "Sunder",
  "Stampede",
  "Cleave",
  "Heavy Strike",
  "Rolling Slam",
  "Armour Explosion",
  "Ground Slam",
  "Infernal Cry",
  "Shockwave Totem",
  "Molten Strike",
  "Shield Charge",
  "Leap Slam",

  // Ranger
  "Ice Shot",
  "Explosive Shot",
  "Galvanic Shards",
  "Lightning Arrow",
  "Barrage",
  "Tornado Shot",
  "Rapid Shot",
  "Rain of Arrows",
  "Shrapnel Ballista",
  "Gas Arrow",
  "Scattershot",

  // Witch
  "Detonate Dead",
  "Raise Zombie",
  "Skeletal Warrior",
  "Bone Storm",
  "Skeletal Mage",
  "Summon Raging Spirits",
  "Unearth",
  "Essence Drain",
  "Contagion",
  "Blight",
  "Pain Offering",

  // Sorceress
  "Fireball",
  "Lightning Bolt",
  "Freezing Shards",
  "Comet",
  "Arc",
  "Glacial Cascade",
  "Orb of Storms",
  "Flameblast",
  "Cold Snap",
  "Volcanic Fissure",
  "Ball Lightning",
  "Spark",
  "Frost Bomb",
  "Fire Wall",
  "Ice Nova",

  // Monk
  "Tempest Bell",
  "Rolling Thunder",
  "Falling Thunder",
  "Hand of Chayula",
  "Killing Palm",
  "Whirling Assault",
  "Herald of Thunder",
  "Staggering Palm",
  "Flicker Strike",

  // Mercenary
  "Fragmentation Rounds",
  "Explosive Grenade",
  "Gas Grenade",
  "Flash Grenade",
  "Incendiary Shot",
  "Glacial Bolt",
  "Voltaic Grenade",

  // General / Cross-class
  "Whirling Blades",
  "Dash",
  "Flame Wall",
  "Sniper's Mark",
  "Conductivity",
  "Flammability",
  "Frostbite",
];
